2021-07-30T02:16:37,902 Using pip 21.2.1 from /home/admin/mct/.venv/lib/python3.8/site-packages/pip (python 3.8)
2021-07-30T02:16:37,902 Non-user install because user site-packages disabled
2021-07-30T02:16:37,911 Created temporary directory: /tmp/pip-ephem-wheel-cache-e4xm6j7r
2021-07-30T02:16:37,912 Created temporary directory: /tmp/pip-req-tracker-kwc7tph0
2021-07-30T02:16:37,912 Initialized build tracking at /tmp/pip-req-tracker-kwc7tph0
2021-07-30T02:16:37,912 Created build tracker: /tmp/pip-req-tracker-kwc7tph0
2021-07-30T02:16:37,912 Entered build tracker: /tmp/pip-req-tracker-kwc7tph0
2021-07-30T02:16:37,912 Created temporary directory: /tmp/pip-install-93fnxuv5
2021-07-30T02:16:37,924 Processing /home/admin/mct
2021-07-30T02:16:37,924   Added file:///home/admin/mct to build tracker '/tmp/pip-req-tracker-kwc7tph0'
2021-07-30T02:16:37,925   Created temporary directory: /tmp/pip-build-env-zna0p2kv
2021-07-30T02:16:37,927   Created temporary directory: /tmp/pip-standalone-pip-e28sxld6
2021-07-30T02:16:38,045   Running command /home/admin/mct/.venv/bin/python /tmp/pip-standalone-pip-e28sxld6/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-zna0p2kv/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel
2021-07-30T02:16:39,024   Using pip 21.2.1 from /tmp/pip-standalone-pip-e28sxld6/__env_pip__.zip/pip (python 3.8)
2021-07-30T02:16:39,573   Collecting setuptools
2021-07-30T02:16:39,577     Using cached setuptools-57.4.0-py3-none-any.whl (819 kB)
2021-07-30T02:16:39,651   Collecting wheel
2021-07-30T02:16:39,653     Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
2021-07-30T02:16:39,752   Installing collected packages: wheel, setuptools
2021-07-30T02:16:39,774     Creating /tmp/pip-build-env-zna0p2kv/overlay/bin
2021-07-30T02:16:39,774     changing mode of /tmp/pip-build-env-zna0p2kv/overlay/bin/wheel to 755
2021-07-30T02:16:40,064   Successfully installed setuptools-57.4.0 wheel-0.36.2
2021-07-30T02:16:40,115   Running command /home/admin/mct/.venv/bin/python /home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpp66aw4oq
2021-07-30T02:16:40,283   Traceback (most recent call last):
2021-07-30T02:16:40,283     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/config.py", line 387, in _parse_attr
2021-07-30T02:16:40,284       return getattr(StaticModule(module_name), attr_name)
2021-07-30T02:16:40,284     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/config.py", line 24, in __init__
2021-07-30T02:16:40,284       spec = importlib.util.find_spec(name)
2021-07-30T02:16:40,284     File "/usr/local/lib/python3.8/importlib/util.py", line 94, in find_spec
2021-07-30T02:16:40,284       parent = __import__(parent_name, fromlist=['__path__'])
2021-07-30T02:16:40,284     File "/home/admin/mct/mct/__init__.py", line 1, in <module>
2021-07-30T02:16:40,284       from .cli import mct
2021-07-30T02:16:40,284     File "/home/admin/mct/mct/cli.py", line 3, in <module>
2021-07-30T02:16:40,284       import click
2021-07-30T02:16:40,284   ModuleNotFoundError: No module named 'click'

2021-07-30T02:16:40,284   During handling of the above exception, another exception occurred:

2021-07-30T02:16:40,284   Traceback (most recent call last):
2021-07-30T02:16:40,284     File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
2021-07-30T02:16:40,284       main()
2021-07-30T02:16:40,284     File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
2021-07-30T02:16:40,284       json_out['return_val'] = hook(**hook_input['kwargs'])
2021-07-30T02:16:40,284     File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
2021-07-30T02:16:40,284       return hook(config_settings)
2021-07-30T02:16:40,284     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
2021-07-30T02:16:40,284       return self._get_build_requires(
2021-07-30T02:16:40,284     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
2021-07-30T02:16:40,284       self.run_setup()
2021-07-30T02:16:40,285     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
2021-07-30T02:16:40,285       exec(compile(code, __file__, 'exec'), locals())
2021-07-30T02:16:40,285     File "setup.py", line 6, in <module>
2021-07-30T02:16:40,285       setuptools.setup()
2021-07-30T02:16:40,285     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
2021-07-30T02:16:40,285       return distutils.core.setup(**attrs)
2021-07-30T02:16:40,285     File "/usr/local/lib/python3.8/distutils/core.py", line 121, in setup
2021-07-30T02:16:40,285       dist.parse_config_files()
2021-07-30T02:16:40,285     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 778, in parse_config_files
2021-07-30T02:16:40,285       parse_configuration(self, self.command_options,
2021-07-30T02:16:40,285     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/config.py", line 157, in parse_configuration
2021-07-30T02:16:40,285       meta.parse()
2021-07-30T02:16:40,285     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/config.py", line 463, in parse
2021-07-30T02:16:40,285       section_parser_method(section_options)
2021-07-30T02:16:40,285     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/config.py", line 436, in parse_section
2021-07-30T02:16:40,285       self[name] = value
2021-07-30T02:16:40,285     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/config.py", line 220, in __setitem__
2021-07-30T02:16:40,285       value = parser(value)
2021-07-30T02:16:40,285     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/config.py", line 557, in _parse_version
2021-07-30T02:16:40,285       version = self._parse_attr(value, self.package_dir)
2021-07-30T02:16:40,285     File "/tmp/pip-build-env-zna0p2kv/overlay/lib/python3.8/site-packages/setuptools/config.py", line 390, in _parse_attr
2021-07-30T02:16:40,285       module = importlib.import_module(module_name)
2021-07-30T02:16:40,285     File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-07-30T02:16:40,285       return _bootstrap._gcd_import(name[level:], package, level)
2021-07-30T02:16:40,285     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-07-30T02:16:40,285     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-07-30T02:16:40,286     File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
2021-07-30T02:16:40,286     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-07-30T02:16:40,286     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-07-30T02:16:40,286     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-07-30T02:16:40,286     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2021-07-30T02:16:40,286     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2021-07-30T02:16:40,286     File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2021-07-30T02:16:40,286     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-07-30T02:16:40,286     File "/home/admin/mct/mct/__init__.py", line 1, in <module>
2021-07-30T02:16:40,286       from .cli import mct
2021-07-30T02:16:40,286     File "/home/admin/mct/mct/cli.py", line 3, in <module>
2021-07-30T02:16:40,286       import click
2021-07-30T02:16:40,286   ModuleNotFoundError: No module named 'click'
2021-07-30T02:16:40,295 WARNING: Discarding file:///home/admin/mct. Command errored out with exit status 1: /home/admin/mct/.venv/bin/python /home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpp66aw4oq Check the logs for full command output.
2021-07-30T02:16:40,296 ERROR: Command errored out with exit status 1: /home/admin/mct/.venv/bin/python /home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpp66aw4oq Check the logs for full command output.
2021-07-30T02:16:40,296 Exception information:
2021-07-30T02:16:40,296 Traceback (most recent call last):
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
2021-07-30T02:16:40,296     status = self.run(options, args)
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
2021-07-30T02:16:40,296     return func(self, options, args)
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 315, in run
2021-07-30T02:16:40,296     requirement_set = resolver.resolve(
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
2021-07-30T02:16:40,296     collected = self.factory.collect_root_requirements(root_reqs)
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 471, in collect_root_requirements
2021-07-30T02:16:40,296     req = self._make_requirement_from_install_req(
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 448, in _make_requirement_from_install_req
2021-07-30T02:16:40,296     raise self._build_failures[ireq.link]
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 204, in _make_candidate_from_link
2021-07-30T02:16:40,296     self._link_candidate_cache[link] = LinkCandidate(
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 295, in __init__
2021-07-30T02:16:40,296     super().__init__(
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
2021-07-30T02:16:40,296     self.dist = self._prepare()
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
2021-07-30T02:16:40,296     dist = self._prepare_distribution()
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 305, in _prepare_distribution
2021-07-30T02:16:40,296     return self._factory.preparer.prepare_linked_requirement(
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
2021-07-30T02:16:40,296     return self._prepare_linked_requirement(req, parallel_builds)
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
2021-07-30T02:16:40,296     dist = _get_prepared_distribution(
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
2021-07-30T02:16:40,296     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 34, in prepare_distribution_metadata
2021-07-30T02:16:40,296     self._setup_isolation(finder)
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 88, in _setup_isolation
2021-07-30T02:16:40,296     reqs = backend.get_requires_for_build_wheel()
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 168, in get_requires_for_build_wheel
2021-07-30T02:16:40,296     return self._call_hook('get_requires_for_build_wheel', {
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 318, in _call_hook
2021-07-30T02:16:40,296     self._subprocess_runner(
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 274, in runner
2021-07-30T02:16:40,296     call_subprocess(
2021-07-30T02:16:40,296   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
2021-07-30T02:16:40,296     raise InstallationSubprocessError(proc.returncode, command_desc)
2021-07-30T02:16:40,296 pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/admin/mct/.venv/bin/python /home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpp66aw4oq Check the logs for full command output.
2021-07-30T02:16:40,300 Removed file:///home/admin/mct from build tracker '/tmp/pip-req-tracker-kwc7tph0'
2021-07-30T02:16:40,300 Removed build tracker: '/tmp/pip-req-tracker-kwc7tph0'
2021-07-30T02:17:14,736 Using pip 21.2.1 from /home/admin/mct/.venv/lib/python3.8/site-packages/pip (python 3.8)
2021-07-30T02:17:14,736 Non-user install because user site-packages disabled
2021-07-30T02:17:14,745 Created temporary directory: /tmp/pip-ephem-wheel-cache-88b9h67h
2021-07-30T02:17:14,745 Created temporary directory: /tmp/pip-req-tracker-zkvovemf
2021-07-30T02:17:14,745 Initialized build tracking at /tmp/pip-req-tracker-zkvovemf
2021-07-30T02:17:14,745 Created build tracker: /tmp/pip-req-tracker-zkvovemf
2021-07-30T02:17:14,745 Entered build tracker: /tmp/pip-req-tracker-zkvovemf
2021-07-30T02:17:14,745 Created temporary directory: /tmp/pip-install-ctob3503
2021-07-30T02:17:14,757 Processing /home/admin/mct
2021-07-30T02:17:14,757   Added file:///home/admin/mct to build tracker '/tmp/pip-req-tracker-zkvovemf'
2021-07-30T02:17:14,758   Created temporary directory: /tmp/pip-build-env-5vpm5spi
2021-07-30T02:17:14,760   Created temporary directory: /tmp/pip-standalone-pip-r6zdqkeu
2021-07-30T02:17:14,877   Running command /home/admin/mct/.venv/bin/python /tmp/pip-standalone-pip-r6zdqkeu/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5vpm5spi/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel
2021-07-30T02:17:15,858   Using pip 21.2.1 from /tmp/pip-standalone-pip-r6zdqkeu/__env_pip__.zip/pip (python 3.8)
2021-07-30T02:17:16,403   Collecting setuptools
2021-07-30T02:17:16,406     Using cached setuptools-57.4.0-py3-none-any.whl (819 kB)
2021-07-30T02:17:16,481   Collecting wheel
2021-07-30T02:17:16,483     Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
2021-07-30T02:17:16,585   Installing collected packages: wheel, setuptools
2021-07-30T02:17:16,606     Creating /tmp/pip-build-env-5vpm5spi/overlay/bin
2021-07-30T02:17:16,606     changing mode of /tmp/pip-build-env-5vpm5spi/overlay/bin/wheel to 755
2021-07-30T02:17:16,899   Successfully installed setuptools-57.4.0 wheel-0.36.2
2021-07-30T02:17:16,952   Running command /home/admin/mct/.venv/bin/python /home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpeer8bicp
2021-07-30T02:17:17,121   Traceback (most recent call last):
2021-07-30T02:17:17,121     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/config.py", line 387, in _parse_attr
2021-07-30T02:17:17,121       return getattr(StaticModule(module_name), attr_name)
2021-07-30T02:17:17,121     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/config.py", line 24, in __init__
2021-07-30T02:17:17,121       spec = importlib.util.find_spec(name)
2021-07-30T02:17:17,121     File "/usr/local/lib/python3.8/importlib/util.py", line 94, in find_spec
2021-07-30T02:17:17,121       parent = __import__(parent_name, fromlist=['__path__'])
2021-07-30T02:17:17,121     File "/home/admin/mct/mct/__init__.py", line 1, in <module>
2021-07-30T02:17:17,121       from .cli import mct
2021-07-30T02:17:17,121     File "/home/admin/mct/mct/cli.py", line 3, in <module>
2021-07-30T02:17:17,121       import click
2021-07-30T02:17:17,121   ModuleNotFoundError: No module named 'click'

2021-07-30T02:17:17,121   During handling of the above exception, another exception occurred:

2021-07-30T02:17:17,121   Traceback (most recent call last):
2021-07-30T02:17:17,121     File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
2021-07-30T02:17:17,121       main()
2021-07-30T02:17:17,121     File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
2021-07-30T02:17:17,121       json_out['return_val'] = hook(**hook_input['kwargs'])
2021-07-30T02:17:17,121     File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
2021-07-30T02:17:17,122       return hook(config_settings)
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
2021-07-30T02:17:17,122       return self._get_build_requires(
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
2021-07-30T02:17:17,122       self.run_setup()
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
2021-07-30T02:17:17,122       exec(compile(code, __file__, 'exec'), locals())
2021-07-30T02:17:17,122     File "setup.py", line 6, in <module>
2021-07-30T02:17:17,122       setuptools.setup()
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
2021-07-30T02:17:17,122       return distutils.core.setup(**attrs)
2021-07-30T02:17:17,122     File "/usr/local/lib/python3.8/distutils/core.py", line 121, in setup
2021-07-30T02:17:17,122       dist.parse_config_files()
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 778, in parse_config_files
2021-07-30T02:17:17,122       parse_configuration(self, self.command_options,
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/config.py", line 157, in parse_configuration
2021-07-30T02:17:17,122       meta.parse()
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/config.py", line 463, in parse
2021-07-30T02:17:17,122       section_parser_method(section_options)
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/config.py", line 436, in parse_section
2021-07-30T02:17:17,122       self[name] = value
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/config.py", line 220, in __setitem__
2021-07-30T02:17:17,122       value = parser(value)
2021-07-30T02:17:17,122     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/config.py", line 557, in _parse_version
2021-07-30T02:17:17,122       version = self._parse_attr(value, self.package_dir)
2021-07-30T02:17:17,123     File "/tmp/pip-build-env-5vpm5spi/overlay/lib/python3.8/site-packages/setuptools/config.py", line 390, in _parse_attr
2021-07-30T02:17:17,123       module = importlib.import_module(module_name)
2021-07-30T02:17:17,123     File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2021-07-30T02:17:17,123       return _bootstrap._gcd_import(name[level:], package, level)
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2021-07-30T02:17:17,123     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-07-30T02:17:17,123     File "/home/admin/mct/mct/__init__.py", line 1, in <module>
2021-07-30T02:17:17,123       from .cli import mct
2021-07-30T02:17:17,123     File "/home/admin/mct/mct/cli.py", line 3, in <module>
2021-07-30T02:17:17,123       import click
2021-07-30T02:17:17,123   ModuleNotFoundError: No module named 'click'
2021-07-30T02:17:17,133 WARNING: Discarding file:///home/admin/mct. Command errored out with exit status 1: /home/admin/mct/.venv/bin/python /home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpeer8bicp Check the logs for full command output.
2021-07-30T02:17:17,133 ERROR: Command errored out with exit status 1: /home/admin/mct/.venv/bin/python /home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpeer8bicp Check the logs for full command output.
2021-07-30T02:17:17,133 Exception information:
2021-07-30T02:17:17,133 Traceback (most recent call last):
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
2021-07-30T02:17:17,133     status = self.run(options, args)
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
2021-07-30T02:17:17,133     return func(self, options, args)
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 315, in run
2021-07-30T02:17:17,133     requirement_set = resolver.resolve(
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
2021-07-30T02:17:17,133     collected = self.factory.collect_root_requirements(root_reqs)
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 471, in collect_root_requirements
2021-07-30T02:17:17,133     req = self._make_requirement_from_install_req(
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 448, in _make_requirement_from_install_req
2021-07-30T02:17:17,133     raise self._build_failures[ireq.link]
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 204, in _make_candidate_from_link
2021-07-30T02:17:17,133     self._link_candidate_cache[link] = LinkCandidate(
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 295, in __init__
2021-07-30T02:17:17,133     super().__init__(
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
2021-07-30T02:17:17,133     self.dist = self._prepare()
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
2021-07-30T02:17:17,133     dist = self._prepare_distribution()
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 305, in _prepare_distribution
2021-07-30T02:17:17,133     return self._factory.preparer.prepare_linked_requirement(
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
2021-07-30T02:17:17,133     return self._prepare_linked_requirement(req, parallel_builds)
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
2021-07-30T02:17:17,133     dist = _get_prepared_distribution(
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
2021-07-30T02:17:17,133     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 34, in prepare_distribution_metadata
2021-07-30T02:17:17,133     self._setup_isolation(finder)
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 88, in _setup_isolation
2021-07-30T02:17:17,133     reqs = backend.get_requires_for_build_wheel()
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 168, in get_requires_for_build_wheel
2021-07-30T02:17:17,133     return self._call_hook('get_requires_for_build_wheel', {
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 318, in _call_hook
2021-07-30T02:17:17,133     self._subprocess_runner(
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 274, in runner
2021-07-30T02:17:17,133     call_subprocess(
2021-07-30T02:17:17,133   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
2021-07-30T02:17:17,133     raise InstallationSubprocessError(proc.returncode, command_desc)
2021-07-30T02:17:17,133 pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/admin/mct/.venv/bin/python /home/admin/mct/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpeer8bicp Check the logs for full command output.
2021-07-30T02:17:17,137 Removed file:///home/admin/mct from build tracker '/tmp/pip-req-tracker-zkvovemf'
2021-07-30T02:17:17,137 Removed build tracker: '/tmp/pip-req-tracker-zkvovemf'
2021-07-30T02:18:59,022 Using pip 21.2.1 from /home/admin/mct/.venv/lib/python3.8/site-packages/pip (python 3.8)
2021-07-30T02:18:59,022 Non-user install because user site-packages disabled
2021-07-30T02:18:59,031 Created temporary directory: /tmp/pip-ephem-wheel-cache-b0w4bet5
2021-07-30T02:18:59,031 Created temporary directory: /tmp/pip-req-tracker-s2ehxbnx
2021-07-30T02:18:59,031 Initialized build tracking at /tmp/pip-req-tracker-s2ehxbnx
2021-07-30T02:18:59,031 Created build tracker: /tmp/pip-req-tracker-s2ehxbnx
2021-07-30T02:18:59,031 Entered build tracker: /tmp/pip-req-tracker-s2ehxbnx
2021-07-30T02:18:59,032 Created temporary directory: /tmp/pip-install-lmqi1pbi
2021-07-30T02:18:59,043 Processing /home/admin/mct
2021-07-30T02:18:59,044   Added file:///home/admin/mct to build tracker '/tmp/pip-req-tracker-s2ehxbnx'
2021-07-30T02:18:59,044 ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
2021-07-30T02:18:59,044 Exception information:
2021-07-30T02:18:59,044 Traceback (most recent call last):
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
2021-07-30T02:18:59,044     status = self.run(options, args)
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 203, in wrapper
2021-07-30T02:18:59,044     return func(self, options, args)
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 315, in run
2021-07-30T02:18:59,044     requirement_set = resolver.resolve(
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
2021-07-30T02:18:59,044     collected = self.factory.collect_root_requirements(root_reqs)
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 471, in collect_root_requirements
2021-07-30T02:18:59,044     req = self._make_requirement_from_install_req(
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 433, in _make_requirement_from_install_req
2021-07-30T02:18:59,044     cand = self._make_candidate_from_link(
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 204, in _make_candidate_from_link
2021-07-30T02:18:59,044     self._link_candidate_cache[link] = LinkCandidate(
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 295, in __init__
2021-07-30T02:18:59,044     super().__init__(
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
2021-07-30T02:18:59,044     self.dist = self._prepare()
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
2021-07-30T02:18:59,044     dist = self._prepare_distribution()
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 305, in _prepare_distribution
2021-07-30T02:18:59,044     return self._factory.preparer.prepare_linked_requirement(
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
2021-07-30T02:18:59,044     return self._prepare_linked_requirement(req, parallel_builds)
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
2021-07-30T02:18:59,044     dist = _get_prepared_distribution(
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
2021-07-30T02:18:59,044     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 29, in prepare_distribution_metadata
2021-07-30T02:18:59,044     self.req.load_pyproject_toml()
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 474, in load_pyproject_toml
2021-07-30T02:18:59,044     pyproject_toml_data = load_pyproject_toml(
2021-07-30T02:18:59,044   File "/home/admin/mct/.venv/lib/python3.8/site-packages/pip/_internal/pyproject.py", line 82, in load_pyproject_toml
2021-07-30T02:18:59,044     raise InstallationError(
2021-07-30T02:18:59,044 pip._internal.exceptions.InstallationError: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
2021-07-30T02:18:59,047 Removed file:///home/admin/mct from build tracker '/tmp/pip-req-tracker-s2ehxbnx'
2021-07-30T02:18:59,047 Removed build tracker: '/tmp/pip-req-tracker-s2ehxbnx'
